In [17]:
import numpy as np
import matplotlib.pyplot as plt

In [18]:
Ex=np.zeros((3,3))

In [19]:
mu=np.zeros((3,1))
mu[0,0]=18
mu[1,0]=18
mu[2,0]=18

In [20]:
mu

array([[18.],
       [18.],
       [18.]])

In [21]:
y=np.zeros((2,1))
y[0,0]=16
y[1,0]=23

In [22]:
Ex[0,0]=1
Ex[0,1]=0.61
Ex[0,2]=0.22
Ex[1,0]=0.61
Ex[1,1]=1
Ex[1,2]=0.37
Ex[2,0]=0.22
Ex[2,1]=0.37
Ex[2,2]=1

In [23]:
Ex

array([[1.  , 0.61, 0.22],
       [0.61, 1.  , 0.37],
       [0.22, 0.37, 1.  ]])

In [24]:
Ey=np.zeros((2,2))

In [25]:

Ey[0,0]=0.5
Ey[1,1]=0.5

In [26]:
H=np.zeros((2,3))
H[0,1]=1
H[1,2]=1

In [27]:
H

array([[0., 1., 0.],
       [0., 0., 1.]])

In [28]:

Ey

array([[0.5, 0. ],
       [0. , 0.5]])

In [29]:
Ht=np.zeros((3,2))

In [30]:
Ht[1,0]=1
Ht[2,1]=1

In [31]:
Ht

array([[0., 0.],
       [1., 0.],
       [0., 1.]])

In [21]:
K=Ex@Ht@np.linalg.inv(Ey+H@Ex@Ht)

In [22]:
K

array([[0.39449151, 0.04935876],
       [0.64507122, 0.0875491 ],
       [0.0875491 , 0.64507122]])

In [23]:
mu_star=mu+K@(y-H@mu)

In [24]:
mu_star

array([[17.4578108 ],
       [17.14760305],
       [21.05025791]])

In [25]:
covariance_star=(np.identity(3)-K@H)@Ex

In [26]:
covariance_star

array([[0.74850125, 0.19724575, 0.02467938],
       [0.19724575, 0.32253561, 0.04377455],
       [0.02467938, 0.04377455, 0.32253561]])

In [27]:
K@H

array([[0.        , 0.39449151, 0.04935876],
       [0.        , 0.64507122, 0.0875491 ],
       [0.        , 0.0875491 , 0.64507122]])

# b

In [28]:
np.array([[1,2,3],[2,3,4],[4,5,6]])

array([[1, 2, 3],
       [2, 3, 4],
       [4, 5, 6]])

In [32]:
u1=np.array([[18],[18],[18]])

In [37]:
mu_star1=u1+k@(y-H@u1)
mu_star1

array([[18.        ],
       [16.66666667],
       [21.33333333]])

In [15]:
EX_1=np.identity(3)
EX_1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:
k=EX_1@Ht@np.linalg.inv(Ey+H@EX_1@Ht)

In [38]:
k

array([[0.        , 0.        ],
       [0.66666667, 0.        ],
       [0.        , 0.66666667]])

In [42]:
covariance_star1=(np.identity(3)-k@H)@EX_1

In [43]:
covariance_star1

array([[1.        , 0.        , 0.        ],
       [0.        , 0.33333333, 0.        ],
       [0.        , 0.        , 0.33333333]])