In [1]:
import numpy as np

lst=[2,3,4,5]
x=np.array(lst)
x

array([2, 3, 4, 5])

In [2]:
x.shape #number of elements in the array

(4,)

In [3]:
x=np.linspace(0,4,9,endpoint=False)
x

array([0.        , 0.44444444, 0.88888889, 1.33333333, 1.77777778,
       2.22222222, 2.66666667, 3.11111111, 3.55555556])

In [4]:
m=np.array([[1,3],[0,-1]])
m

array([[ 1,  3],
       [ 0, -1]])

In [5]:
m.shape

(2, 2)

In [16]:
x=np.ones(5)
x

array([1., 1., 1., 1., 1.])

In [18]:
y=np.zero([4,5])
y

AttributeError: module 'numpy' has no attribute 'zero'

In [7]:
m=np.array([[1,3],[0,-1]],dtype=float)
m

array([[ 1.,  3.],
       [ 0., -1.]])

In [6]:
import numpy as np
c=np.linspace(0,1,21)
c

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95, 1.  ])

In [9]:
c.shape

(21,)

In [7]:
c.shape=3,7
c

array([[0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 ],
       [0.35, 0.4 , 0.45, 0.5 , 0.55, 0.6 , 0.65],
       [0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95, 1.  ]])

In [8]:
c.shape=7,3
c

array([[0.  , 0.05, 0.1 ],
       [0.15, 0.2 , 0.25],
       [0.3 , 0.35, 0.4 ],
       [0.45, 0.5 , 0.55],
       [0.6 , 0.65, 0.7 ],
       [0.75, 0.8 , 0.85],
       [0.9 , 0.95, 1.  ]])

In [20]:
b=c.astype(complex)
b

array([[0.  +0.j, 0.05+0.j, 0.1 +0.j],
       [0.15+0.j, 0.2 +0.j, 0.25+0.j],
       [0.3 +0.j, 0.35+0.j, 0.4 +0.j],
       [0.45+0.j, 0.5 +0.j, 0.55+0.j],
       [0.6 +0.j, 0.65+0.j, 0.7 +0.j],
       [0.75+0.j, 0.8 +0.j, 0.85+0.j],
       [0.9 +0.j, 0.95+0.j, 1.  +0.j]])

In [9]:
c

array([[0.  , 0.05, 0.1 ],
       [0.15, 0.2 , 0.25],
       [0.3 , 0.35, 0.4 ],
       [0.45, 0.5 , 0.55],
       [0.6 , 0.65, 0.7 ],
       [0.75, 0.8 , 0.85],
       [0.9 , 0.95, 1.  ]])

In [22]:
c[1]  #returns row 2

array([0.15, 0.2 , 0.25])

In [23]:
c[1:6]  #return row from 2nd index to 6

array([[0.15, 0.2 , 0.25],
       [0.3 , 0.35, 0.4 ],
       [0.45, 0.5 , 0.55],
       [0.6 , 0.65, 0.7 ],
       [0.75, 0.8 , 0.85]])

In [24]:
c[1:3]  #row manipulation

array([[0.15, 0.2 , 0.25],
       [0.3 , 0.35, 0.4 ]])

In [10]:
c[0:3:2]

array([[0.  , 0.05, 0.1 ],
       [0.3 , 0.35, 0.4 ]])

In [27]:
c[:,0] #extracting th column

array([0.  , 0.15, 0.3 , 0.45, 0.6 , 0.75, 0.9 ])

In [4]:
c

NameError: name 'c' is not defined

In [11]:
c[:,:0]  #index starts from zero to n-1

array([], shape=(7, 0), dtype=float64)

In [31]:
c[:,1]

array([0.05, 0.2 , 0.35, 0.5 , 0.65, 0.8 , 0.95])

In [33]:
c[:,1:3] #from index 1 to index 3 excluding 3-of course

array([[0.05, 0.1 ],
       [0.2 , 0.25],
       [0.35, 0.4 ],
       [0.5 , 0.55],
       [0.65, 0.7 ],
       [0.8 , 0.85],
       [0.95, 1.  ]])

In [37]:
c

array([[0.  , 0.05, 0.1 ],
       [0.15, 0.2 , 0.25],
       [0.3 , 0.35, 0.4 ],
       [0.45, 0.5 , 0.55],
       [0.6 , 0.65, 0.7 ],
       [0.75, 0.8 , 0.85],
       [0.9 , 0.95, 1.  ]])

In [38]:
c[3,2] #the element of the column

0.55

In [2]:
import numpy as np

x=np.linspace(1,5,21)
x

array([1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4,
       3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. ])

In [3]:
a=np.arange(2,15,0.5)
a

array([ 2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,  6.5,  7. ,
        7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5, 11. , 11.5, 12. , 12.5,
       13. , 13.5, 14. , 14.5])

In [4]:
def seq(n):
    return[i for i in range(n+1)]
seq(12)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [8]:
c=np.array(seq(12))
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [11]:
t=np.zeros(5)
t

array([0., 0., 0., 0., 0.])

In [15]:
y=np.linspace(0,15,3)
y

array([ 0. ,  7.5, 15. ])

In [24]:
import numpy as np
e=np.array([2,3],[4,5],dtype=float)
e

TypeError: data type not understood

In [25]:
m=np.array([[1,3],[0,-1]])
m

array([[ 1,  3],
       [ 0, -1]])

In [33]:
e=np.array([[1,3,5,6,3,5,],[3,5,6,3,6,3],[5,2,4,2,5,2,5]], dtype=float)
e.reshape(2,3)
e

ValueError: setting an array element with a sequence.

In [39]:
import numpy as np
e=np.linspace(1,13,21)
e

array([ 1. ,  1.6,  2.2,  2.8,  3.4,  4. ,  4.6,  5.2,  5.8,  6.4,  7. ,
        7.6,  8.2,  8.8,  9.4, 10. , 10.6, 11.2, 11.8, 12.4, 13. ])

In [43]:
e.shape=3,7
e

array([[ 1. ,  1.6,  2.2,  2.8,  3.4,  4. ,  4.6],
       [ 5.2,  5.8,  6.4,  7. ,  7.6,  8.2,  8.8],
       [ 9.4, 10. , 10.6, 11.2, 11.8, 12.4, 13. ]])

In [44]:
e.shape

(3, 7)

In [48]:
e[1:2]

array([[5.2, 5.8, 6.4, 7. , 7.6, 8.2, 8.8]])

In [49]:
e[1:2:1,1:2:1]

array([[5.8]])

In [50]:
f=e.astype(int)
f

array([[ 1,  1,  2,  2,  3,  4,  4],
       [ 5,  5,  6,  7,  7,  8,  8],
       [ 9, 10, 10, 11, 11, 12, 13]])

In [53]:
y=np.ones(1)
z=np.zeros(2)


array([1., 1.])

In [54]:
e

array([[ 1. ,  1.6,  2.2,  2.8,  3.4,  4. ,  4.6],
       [ 5.2,  5.8,  6.4,  7. ,  7.6,  8.2,  8.8],
       [ 9.4, 10. , 10.6, 11.2, 11.8, 12.4, 13. ]])

In [59]:
e[:,2:0:1]

array([], shape=(3, 0), dtype=float64)

In [61]:
d=np.arange(21)
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [63]:
d.shape=7,3
d

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

In [64]:
d.shape

(7, 3)

In [65]:
d.reshape(3,7)

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20]])

In [66]:
d

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

In [67]:
d[0]

array([0, 1, 2])

In [71]:
d[-2]

array([15, 16, 17])

In [75]:
d

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

In [79]:
e=np.arange(18)
e

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [81]:
e.shape=9,2
e

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17]])

In [83]:
e.shape=1,-1
e

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17]])

In [88]:
d=e.astype(complex)
d

array([[ 0.+0.j,  1.+0.j,  2.+0.j,  3.+0.j,  4.+0.j,  5.+0.j,  6.+0.j,
         7.+0.j,  8.+0.j,  9.+0.j, 10.+0.j, 11.+0.j, 12.+0.j, 13.+0.j,
        14.+0.j, 15.+0.j, 16.+0.j, 17.+0.j]])

In [89]:
g=np.array([[2,4,3],[1,3,4],[2,5,7]], dtype=float)
g


array([[2., 4., 3.],
       [1., 3., 4.],
       [2., 5., 7.]])

In [93]:
d=g.shape=1,9
d

(1, 9)

In [92]:
g

array([[2., 4., 3., 1., 3., 4., 2., 5., 7.]])

In [94]:
d

(1, 9)

In [95]:
g

array([[2., 4., 3., 1., 3., 4., 2., 5., 7.]])

In [97]:
g.shape=3,3
g

array([[2., 4., 3.],
       [1., 3., 4.],
       [2., 5., 7.]])

In [100]:
g[0:,2]

array([3., 4., 7.])

In [102]:
import numpy as np

a=np.array([2,5,6])
a

array([2, 5, 6])

In [104]:
lst=[2,3,5,6,7]

c=np.array(lst)
c

array([2, 3, 5, 6, 7])

In [105]:
d=np.arange(1,4,0.5)
d

array([1. , 1.5, 2. , 2.5, 3. , 3.5])

In [107]:
e=np.linspace(1,4,20)
e

array([1.        , 1.15789474, 1.31578947, 1.47368421, 1.63157895,
       1.78947368, 1.94736842, 2.10526316, 2.26315789, 2.42105263,
       2.57894737, 2.73684211, 2.89473684, 3.05263158, 3.21052632,
       3.36842105, 3.52631579, 3.68421053, 3.84210526, 4.        ])

In [110]:
w=np.zeros(5)
w

array([0., 0., 0., 0., 0.])

In [115]:
u=np.linspace(1,2,7)
u

array([1.        , 1.16666667, 1.33333333, 1.5       , 1.66666667,
       1.83333333, 2.        ])

In [116]:
u[0]

1.0

In [117]:
u[-1]

2.0

In [122]:
u[1:6:4]

array([1.16666667, 1.83333333])

In [123]:
u[2:5]

array([1.33333333, 1.5       , 1.66666667])

In [124]:
[]u[1:6:5]

array([1.16666667])

In [126]:
m=np.array([[2,4],[4,5]],dtype=float)
m

array([[2., 4.],
       [4., 5.]])

In [128]:
m.astype(complex)

array([[2.+0.j, 4.+0.j],
       [4.+0.j, 5.+0.j]])

In [130]:
m=np.linspace(1,4,10)
m

array([1.        , 1.33333333, 1.66666667, 2.        , 2.33333333,
       2.66666667, 3.        , 3.33333333, 3.66666667, 4.        ])

In [132]:
m.shape=2,5
m

array([[1.        , 1.33333333, 1.66666667, 2.        , 2.33333333],
       [2.66666667, 3.        , 3.33333333, 3.66666667, 4.        ]])

In [134]:
m.shape=5,2
m

array([[1.        , 1.33333333],
       [1.66666667, 2.        ],
       [2.33333333, 2.66666667],
       [3.        , 3.33333333],
       [3.66666667, 4.        ]])

In [135]:
m[2,1:2]

array([2.66666667])

In [136]:
m=np.linspace(1,7,15)
m

array([1.        , 1.42857143, 1.85714286, 2.28571429, 2.71428571,
       3.14285714, 3.57142857, 4.        , 4.42857143, 4.85714286,
       5.28571429, 5.71428571, 6.14285714, 6.57142857, 7.        ])

In [137]:
m.shape

(15,)

In [139]:
m.shape=3,5
m

array([[1.        , 1.42857143, 1.85714286, 2.28571429, 2.71428571],
       [3.14285714, 3.57142857, 4.        , 4.42857143, 4.85714286],
       [5.28571429, 5.71428571, 6.14285714, 6.57142857, 7.        ]])

In [141]:
m[1,2]

4.0

In [142]:
m[2,4]

7.0

In [143]:
m[0]

array([1.        , 1.42857143, 1.85714286, 2.28571429, 2.71428571])

In [145]:
m[:,2]

array([1.85714286, 4.        , 6.14285714])

In [146]:
m

array([[1.        , 1.42857143, 1.85714286, 2.28571429, 2.71428571],
       [3.14285714, 3.57142857, 4.        , 4.42857143, 4.85714286],
       [5.28571429, 5.71428571, 6.14285714, 6.57142857, 7.        ]])

In [148]:
m.shape=5,3

In [150]:
m=np.linspace(1,3,6)
m

array([1. , 1.4, 1.8, 2.2, 2.6, 3. ])

In [152]:
m.shape=2,3
m

array([[1. , 1.4, 1.8],
       [2.2, 2.6, 3. ]])

In [153]:
m

array([[1. , 1.4, 1.8],
       [2.2, 2.6, 3. ]])

In [155]:
m.shape=1,-1
m

array([[1. , 1.4, 1.8, 2.2, 2.6, 3. ]])

In [156]:
m

array([[1. , 1.4, 1.8, 2.2, 2.6, 3. ]])

In [158]:
m.shape=3,2
m

array([[1. , 1.4],
       [1.8, 2.2],
       [2.6, 3. ]])

In [161]:
m.astype(float)

array([[1. , 1.4],
       [1.8, 2.2],
       [2.6, 3. ]])

In [163]:
m[1,1]

2.2

In [165]:
v=np.linspace(2,3,9)
v

array([2.   , 2.125, 2.25 , 2.375, 2.5  , 2.625, 2.75 , 2.875, 3.   ])

In [166]:
v.shape=3,3
v

array([[2.   , 2.125, 2.25 ],
       [2.375, 2.5  , 2.625],
       [2.75 , 2.875, 3.   ]])

In [169]:
v[2,1:3]

array([2.875, 3.   ])

In [170]:
v[1,1]

2.5

In [172]:
v[1,0:2]

array([2.375, 2.5  ])

In [173]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [177]:
t=np.zeros((5,3))
t

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [179]:
t[0,1]=5
t

array([[0., 5., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [1]:
import numpy as np

c=np.linspace(2,4,9)
c

array([2.  , 2.25, 2.5 , 2.75, 3.  , 3.25, 3.5 , 3.75, 4.  ])

In [ ]:
c.shape=