In [2]:
import numpy as np
a=np.linspace(1,5,12)
a

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [3]:
a.shape

(12,)

In [5]:
def fu(n):
    if n%2==0:
        return True
    else:
        return False


In [14]:
fu([2,4,5])

TypeError: unsupported operand type(s) for %: 'list' and 'int'

In [15]:
b=np.vectorize(fu)
b([2,3,1])

array([ True, False, False])

In [12]:
x=np.linspace(1,5,12)
f=lambda x: 2*x+1
f(x)

array([ 3.        ,  3.72727273,  4.45454545,  5.18181818,  5.90909091,
        6.63636364,  7.36363636,  8.09090909,  8.81818182,  9.54545455,
       10.27272727, 11.        ])

In [13]:
a

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [16]:
a

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [17]:
5 in a

True

In [18]:
3 in a

False

In [19]:
np.where(a>1,a**2+3,-a)

array([-1.        ,  4.85950413,  5.98347107,  7.37190083,  9.02479339,
       10.94214876, 13.12396694, 15.57024793, 18.28099174, 21.25619835,
       24.49586777, 28.        ])

In [20]:
a

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [22]:
def fn(n):
    if n%2==0:
        return n**n
    else:
        return n**(1/2)


In [23]:
d=np.vectorize(fn)
d(a)

array([1.        , 1.16774842, 1.31425748, 1.44599761, 1.5666989 ,
       1.67874412, 1.78376517, 1.88293774, 1.97714211, 2.06705764,
       2.15322169, 2.23606798])

In [38]:
import numpy as np
x=np.linspace(1,4,5)
fz=x**3+x
fz[0]
fz

array([ 2.      ,  7.109375, 18.125   , 37.578125, 68.      ])

In [31]:
x

array([1.  , 1.75, 2.5 , 3.25, 4.  ])

In [43]:
import numpy as np
x=np.linspace(1,4,5)
fz=lambda x:x**3+x
fz(x)

array([ 2.      ,  7.109375, 18.125   , 37.578125, 68.      ])

In [44]:
a

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [45]:
np.where(a<2,a+1,-a)

array([ 2.        ,  2.36363636,  2.72727273, -2.09090909, -2.45454545,
       -2.81818182, -3.18181818, -3.54545455, -3.90909091, -4.27272727,
       -4.63636364, -5.        ])

In [46]:
a==0

array([False, False, False, False, False, False, False, False, False,
       False, False, False])

In [47]:
a<2

array([ True,  True,  True, False, False, False, False, False, False,
       False, False, False])

In [48]:
a[a<2]

array([1.        , 1.36363636, 1.72727273])

In [51]:
M=np.zeros((5,5))
M

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [55]:
import numpy as np
M
for i in range(5):
    for j in range(5):
        if i==j:
            M[i,j]=4
        elif i==j+1:
            M[i,j]=7
        elif j==i+1:
            M[i,j]=3
        elif i==j+2:
            M[i,j]=-1
        elif j==i+2:
            M[i,j]=1
print(M)

[[ 4.  3.  1.  0.  0.]
 [ 7.  4.  3.  1.  0.]
 [-1.  7.  4.  3.  1.]
 [ 0. -1.  7.  4.  3.]
 [ 0.  0. -1.  7.  4.]]


In [54]:
M[2,2]=10
M

array([[ 4.,  3.,  0.,  0.,  0.],
       [ 7.,  4.,  3.,  0.,  0.],
       [ 0.,  7., 10.,  3.,  0.],
       [ 0.,  0.,  7.,  4.,  3.],
       [ 0.,  0.,  0.,  7.,  4.]])

In [59]:
g=np.array([[3,5],[5,7]])
h=np.array([[4,2],[4,6]])
print(g)
print('##############')
print(h)

[[3 5]
 [5 7]]
##############
[[4 2]
 [4 6]]


In [62]:
g*h

array([[12, 10],
       [20, 42]])

In [63]:
g@h

array([[32, 36],
       [48, 52]])

In [64]:
g

array([[3, 5],
       [5, 7]])

In [65]:
i=g.reshape(1,4)
i

array([[3, 5, 5, 7]])

In [67]:
j=h.reshape(1,4)
j

array([[4, 2, 4, 6]])

In [68]:
i*j

array([[12, 10, 20, 42]])

ValueError: shapes (1,4) and (1,4) not aligned: 4 (dim 1) != 1 (dim 0)

In [71]:
np.diag([2,4,5])

array([[2, 0, 0],
       [0, 4, 0],
       [0, 0, 5]])

In [72]:
np.diag(g)

array([3, 7])

In [73]:
np.trace(g)

10

In [75]:
Z=np.array([[1,2,4,7],[0,3,6,8],[2,1,9,0]])
Z

array([[1, 2, 4, 7],
       [0, 3, 6, 8],
       [2, 1, 9, 0]])

In [80]:
Z

array([[1, 2, 4, 7],
       [0, 3, 6, 8],
       [2, 1, 9, 0]])

In [87]:
Z[0,1]

2

In [88]:
c=np.linspace(1,5,6)
c

array([1. , 1.8, 2.6, 3.4, 4.2, 5. ])

In [90]:
d=c.reshape(3,2)
d

array([[1. , 1.8],
       [2.6, 3.4],
       [4.2, 5. ]])

In [93]:
e=d[0:3,1] 
e

array([1.8, 3.4, 5. ])

In [97]:
f=d[:]
f


array([[1. , 1.8],
       [2.6, 3.4],
       [4.2, 5. ]])

In [98]:
d

array([[1. , 1.8],
       [2.6, 3.4],
       [4.2, 5. ]])

In [2]:
import numpy as np
def sa(n):
    if n>3:
        return n/2
    else:
        return n+2
x=np.linspace(1,4,6)

In [3]:
sa(x)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [4]:
y=np.vectorize(sa)
y(x)

array([3. , 3.6, 4.2, 4.8, 1.7, 2. ])

In [5]:
x

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

In [7]:
f=lambda x:x**+np.sin(30)+np.exp(1/x)

f(x[0])

3.718281828459045

In [8]:
6 in x

False

In [9]:
2 in x

False

In [10]:
x<2

array([ True,  True, False, False, False, False])

In [11]:
x[x<2]

array([1. , 1.6])

In [12]:
np.where(x<2,x*2,x+1)

array([2. , 3.2, 3.2, 3.8, 4.4, 5. ])

In [20]:
z=np.linspace(1,6,6)
z


array([1., 2., 3., 4., 5., 6.])

In [15]:
np.dot(x,z)

ValueError: shapes (6,) and (5,) not aligned: 6 (dim 0) != 5 (dim 0)

In [17]:
x.shape

(6,)

In [21]:
np.dot(x,z)

63.0

In [23]:
c=np.linspace(1,9,9)
c

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [25]:
d=c.reshape(3,3)
d

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [28]:
M=np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [35]:
M=np.zeros((10,10))
for i in range(10):
    for j in range(10):
        if i==j:
            M[i,j]=1
        elif i==j+1:
            M[i,j]=2
        elif j==i+1:
            M[i,j]=4
        elif i==j+2:
            M[i,j]=3
        elif j==i+2:
            M[i,j]=-1
print(M)

[[ 1.  4. -1.  0.  0.  0.  0.  0.  0.  0.]
 [ 2.  1.  4. -1.  0.  0.  0.  0.  0.  0.]
 [ 3.  2.  1.  4. -1.  0.  0.  0.  0.  0.]
 [ 0.  3.  2.  1.  4. -1.  0.  0.  0.  0.]
 [ 0.  0.  3.  2.  1.  4. -1.  0.  0.  0.]
 [ 0.  0.  0.  3.  2.  1.  4. -1.  0.  0.]
 [ 0.  0.  0.  0.  3.  2.  1.  4. -1.  0.]
 [ 0.  0.  0.  0.  0.  3.  2.  1.  4. -1.]
 [ 0.  0.  0.  0.  0.  0.  3.  2.  1.  4.]
 [ 0.  0.  0.  0.  0.  0.  0.  3.  2.  1.]]


In [55]:
M[3,4]=70
M

array([[ 1.,  4., -1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 2.,  1.,  4., -1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 3.,  2.,  1.,  4., -1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  3.,  2.,  1., 70., -1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  3.,  2.,  1.,  4., -1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  3.,  2.,  1.,  4., -1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  3.,  2.,  1.,  4., -1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  3.,  2.,  1.,  4., -1.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  3.,  2.,  1.,  4.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  3.,  2.,  1.]])

In [38]:
w=np.array([[4,6,7],[7,4,6]])
t=np.array([[4,6,2],[1,4,6]])
print(w)
print('############')
print(t)

[[4 6 7]
 [7 4 6]]
############
[[4 6 2]
 [1 4 6]]


In [45]:
w.shape

(2, 3)

In [46]:
t.shape

(2, 3)

In [48]:
b=t.reshape(3,2)
b

array([[4, 6],
       [2, 1],
       [4, 6]])

In [49]:
w@b

array([[56, 72],
       [60, 82]])

In [61]:
r=np.dot(w,b)
r

array([[56, 72],
       [60, 82]])

In [52]:
w*t

array([[16, 36, 14],
       [ 7, 16, 36]])

In [56]:
np.diag(w)

array([4, 4])

In [57]:
np.trace(w)

8

In [62]:
np.linalg.det(r)

271.9999999999999

In [63]:
np.linalg.inv(r)

array([[ 0.30147059, -0.26470588],
       [-0.22058824,  0.20588235]])

In [66]:
r.T

array([[56, 60],
       [72, 82]])

In [69]:
values,vectors=np.linalg.eig(r)
values

array([  2., 136.])

In [70]:
vectors

array([[-0.8       , -0.66896473],
       [ 0.6       , -0.74329415]])

In [74]:
p=np.poly1d([3,4,5,6])
print(np.poly1d(p))

   3     2
3 x + 4 x + 5 x + 6


In [75]:
np.polyval(p,1)

18

In [76]:
q=p**4
print(np.poly1d(q))

    12       11        10        9        8             7             6
81 x  + 432 x  + 1404 x  + 3576 x + 7078 x + 1.158e+04 x + 1.602e+04 x
              5             4             3        2
 + 1.834e+04 x + 1.776e+04 x + 1.423e+04 x + 8856 x + 4320 x + 1296


In [77]:
np.polyval(q,0)

1296

In [78]:
def SeqTerms(n):
    U0=1
    U1=2
    U2=3
    Un=0
    A=np.array([U0,U1,U2])
    if n==0:
        return []
    elif n==1:
        return np.array([U0])
    elif n==2:
        return np.array([U0,U1])
    elif n==3:
        return np.array([U0,U1,U2])
    else:
        for i in range(3,n):
            Un=U2-3*U1+U0
            U0=U1
            U1=U2
            U2=Un
            A=np.append(A,Un)
    return A

In [81]:
SeqTerms(9)

array([  1,   2,   3,  -2,  -9,   0,  25,  16, -59])