In [3]:
import numpy as np
a=np.linspace(1,4,9)
a

array([1.   , 1.375, 1.75 , 2.125, 2.5  , 2.875, 3.25 , 3.625, 4.   ])

In [4]:
print(2*a)

[2.   2.75 3.5  4.25 5.   5.75 6.5  7.25 8.  ]


In [5]:
y=sum(a)#sums up all the elements of a
y

22.5

In [6]:
a

array([1.   , 1.375, 1.75 , 2.125, 2.5  , 2.875, 3.25 , 3.625, 4.   ])

In [7]:
#Vectorization of functions

x=np.linspace(-5,5,1001)
f_x=x**3+3*x**2+3*x+1
f_x_2=np.exp(-x**2)*np.sin(x)+np.cos(x)
f_x[0]


-64.0

In [8]:
x=np.linspace(-5,5,10)
f_x=x**3+3*x**2+3*x+1
f_x_2=np.exp(-x**2)*np.sin(x)+np.cos(x)
f_x[0]
print(f_x)

[-6.40000000e+01 -2.41097394e+01 -5.61865569e+00 -2.96296296e-01
  8.77914952e-02  3.76406036e+00  1.89629630e+01  5.39149520e+01
  1.16850480e+02  2.16000000e+02]


In [8]:
f= lambda x: x**2
f(x)


array([25.        , 15.12345679,  7.71604938,  2.77777778,  0.30864198,
        0.30864198,  2.77777778,  7.71604938, 15.12345679, 25.        ])

In [9]:
def f_(x):  #Defining a function doesn't work with arrays, however we can use lambda.
    if x>0:
        return x**2
    else:
        return x+1
    


In [10]:
f_(x)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [11]:
x

array([-5.        , -3.88888889, -2.77777778, -1.66666667, -0.55555556,
        0.55555556,  1.66666667,  2.77777778,  3.88888889,  5.        ])

In [13]:
c=np.vectorize(f_) #To correct the inability of def.. Fnc to compute!
c(x)

array([-4.        , -2.88888889, -1.77777778, -0.66666667,  0.44444444,
        0.30864198,  2.77777778,  7.71604938, 15.12345679, 25.        ])

In [17]:
v=np.array([-2,-1,0,1,2,3])
v

array([-2, -1,  0,  1,  2,  3])

In [21]:
 def w(x): #vectorization is necessary for complex functions
        if x>0:
            return 2*x
        else:
            return 1-x
        


In [23]:
q=np.vectorize(w)
q(v)

array([3, 2, 1, 2, 4, 6])

In [24]:
q([2,4,5,1]) # vectorization works perfectly with list!

array([ 4,  8, 10,  2])

In [ ]:
#BOOLEAN

In [26]:
v

array([-2, -1,  0,  1,  2,  3])

In [27]:
8 in v

False

In [29]:
v==0 #it checks for all the elements in v and returns true where necessary

array([False, False,  True, False, False, False])

In [31]:
np.where(v<0,-1*v,v) #np.wherecondition,(x,y) returns x when condition is true and y otherwise

array([2, 1, 0, 1, 2, 3])

In [32]:
np.where(v<0,-1*v,v)

<function numpy.where>

In [37]:
lst=[3,-2,5]
y=np.array(lst)
np.where(y<0,-y,y)

array([3, 2, 5])

In [40]:
y

array([ 3, -2,  5])

In [39]:
np.where(y>1,y**2+np.exp(1/y),y)

array([10.39561243, -2.        , 26.22140276])

In [43]:
v

array([-2, -1,  0,  1,  2,  3])

In [42]:
y

array([ 3, -2,  5])

In [49]:
z=np.linspace(1,3,3)
z

array([1., 2., 3.])

In [50]:
y==z #checking if the elements in the two arrays are the same

array([False, False, False])

In [51]:
np.array_equal(y,z) #checks the entire matrix and not the individual elements in it!

False

In [52]:
z<2

array([ True, False, False])

In [53]:
z[z<2]

array([1.])

In [9]:
z

NameError: name 'z' is not defined

In [56]:
z[z<2]

array([1.])

In [57]:
e=np.linspace(-10,10,20)
e

array([-10.        ,  -8.94736842,  -7.89473684,  -6.84210526,
        -5.78947368,  -4.73684211,  -3.68421053,  -2.63157895,
        -1.57894737,  -0.52631579,   0.52631579,   1.57894737,
         2.63157895,   3.68421053,   4.73684211,   5.78947368,
         6.84210526,   7.89473684,   8.94736842,  10.        ])

In [58]:
e[e%2==0] #returns even numbers of list e

array([-10.,  10.])

In [64]:
e[e%2!=0] #returns the list of elements that are odd

array([-8.94736842, -7.89473684, -6.84210526, -5.78947368, -4.73684211,
       -3.68421053, -2.63157895, -1.57894737, -0.52631579,  0.52631579,
        1.57894737,  2.63157895,  3.68421053,  4.73684211,  5.78947368,
        6.84210526,  7.89473684,  8.94736842])

In [66]:
p=np.linspace(-10,10,21)
p

array([-10.,  -9.,  -8.,  -7.,  -6.,  -5.,  -4.,  -3.,  -2.,  -1.,   0.,
         1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.])

In [67]:
p[p%2==1]

array([-9., -7., -5., -3., -1.,  1.,  3.,  5.,  7.,  9.])

In [ ]:
#Arrays and Functions

In [69]:
print(np.dot(y,z)) #computes the dot product of y and z

14.0


In [71]:
x=np.array([-2,1,0,2,3])
np.where(x>0,2*x,1-x)

array([2., 1., 2., 4., 6., 8.])

In [4]:
import numpy as np
i=np.linspace(1,5,9)

def u(x):
    if x%2==0:
        return True
    else:
        return False
    
c=np.vectorize(u)
c(i)


array([False, False,  True, False, False, False,  True, False, False])

In [5]:
np.where(i%2==0,True,False)

array([False, False,  True, False, False, False,  True, False, False])

In [7]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [ ]:
#15th october Array functions and methods

In [8]:
a=np.array([5,6,7,5])
a

array([5, 6, 7, 5])

In [11]:
import numpy as np
b=np.array([[33,5,7,8],[4,5,6,7],[-1,5,7,8],[7,3,5,2]])
b

array([[33,  5,  7,  8],
       [ 4,  5,  6,  7],
       [-1,  5,  7,  8],
       [ 7,  3,  5,  2]])

In [14]:
b[1,1]=7  #manipulating the data on a matrix
b

array([[33,  5,  7,  8],
       [ 4,  7,  6,  7],
       [-1,  5,  7,  8],
       [ 7,  3,  5,  2]])

In [15]:
b.shape

(4, 4)

In [17]:
c=b.reshape(1,16)
c

array([[33,  5,  7,  8,  4,  7,  6,  7, -1,  5,  7,  8,  7,  3,  5,  2]])

In [18]:
b

array([[33,  5,  7,  8],
       [ 4,  7,  6,  7],
       [-1,  5,  7,  8],
       [ 7,  3,  5,  2]])

In [22]:
d=np.array([[[2,4,5],[2,6,7],[1,4,7]],[[6,8,9,],[1,3,7],[2,5,6]]])
d #tensor 

array([[[2, 4, 5],
        [2, 6, 7],
        [1, 4, 7]],

       [[6, 8, 9],
        [1, 3, 7],
        [2, 5, 6]]])

In [23]:
d.shape

(2, 3, 3)

In [27]:
#manipulating a matrix
import numpy as np
M=np.zeros((10,10))
for i in range(10):
    for j in range(10):
        if i==j:
            M[i,j]=2
        elif abs(j-i)==1:
            M[i,j]=-1
print (M)

[[ 2. -1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [-1.  2. -1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0. -1.  2. -1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. -1.  2. -1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0. -1.  2. -1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. -1.  2. -1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0. -1.  2. -1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0. -1.  2. -1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0. -1.  2. -1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0. -1.  2.]]


In [36]:
#manipulating a matrix
import numpy as np
F=np.zeros((10,10))
for i in range(10):
    for j in range(10):
        if i==j:
            M[i,j]=2
        elif j==1+i:
            M[i,j]=-1
        elif j==i-1:
            M[i,j]=1
print (M)

[[ 2. -1.  4.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  2. -1.  4.  0.  0.  0.  0.  0.  0.]
 [ 3.  1.  2. -1.  4.  0.  0.  0.  0.  0.]
 [ 0.  3.  1.  2. -1.  4.  0.  0.  0.  0.]
 [ 0.  0.  3.  1.  2. -1.  4.  0.  0.  0.]
 [ 0.  0.  0.  3.  1.  2. -1.  4.  0.  0.]
 [ 0.  0.  0.  0.  3.  1.  2. -1.  4.  0.]
 [ 0.  0.  0.  0.  0.  3.  1.  2. -1.  4.]
 [ 0.  0.  0.  0.  0.  0.  3.  1.  2. -1.]
 [ 0.  0.  0.  0.  0.  0.  0.  3.  1.  2.]]


In [37]:
import numpy as np
M=np.zeros((10,10))
for i in range(10):
    for j in range(10):
        if i==j:
            M[i,j]=2
        elif j==1+i:
            M[i,j]=-1
        elif j==i-1:
            M[i,j]=1
        elif j==i-2:
            M[i,j]=3
        elif i==j-2:
            M[i,j]=4
print (M)

[[ 2. -1.  4.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  2. -1.  4.  0.  0.  0.  0.  0.  0.]
 [ 3.  1.  2. -1.  4.  0.  0.  0.  0.  0.]
 [ 0.  3.  1.  2. -1.  4.  0.  0.  0.  0.]
 [ 0.  0.  3.  1.  2. -1.  4.  0.  0.  0.]
 [ 0.  0.  0.  3.  1.  2. -1.  4.  0.  0.]
 [ 0.  0.  0.  0.  3.  1.  2. -1.  4.  0.]
 [ 0.  0.  0.  0.  0.  3.  1.  2. -1.  4.]
 [ 0.  0.  0.  0.  0.  0.  3.  1.  2. -1.]
 [ 0.  0.  0.  0.  0.  0.  0.  3.  1.  2.]]


In [48]:
M@F #MATRIX MULTIPLICATION

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [11]:
import numpy as np #
a=np.array([1,2,3])
b=np.array([3,4,5])
a*b
print (a)
print (b)

[1 2 3]
[3 4 5]


In [47]:
np.dot(a,b) #for arays

26

In [58]:
o=np.array([[1,2],[2,1]])
y=np.array([[1,2],[3,4]])
print(o)
print('******')
print(y)

[[1 2]
 [2 1]]
******
[[1 2]
 [3 4]]


In [54]:
o@y   #@ the sign of matrix multiplication

array([[ 7, 10],
       [ 5,  8]])

In [55]:
y@o #matixes are not commutative

array([[ 5,  4],
       [11, 10]])

In [62]:
z=np.diag([1,2,3])

In [63]:
np.diag(o) #the diagonal is the list of elements where indec of matrix i==j

array([1, 1])

In [65]:
np.trace(p.diag([1,2,3])

SyntaxError: unexpected EOF while parsing (<ipython-input-65-33d582d74a32>, line 1)

In [66]:
r=np.array([[1,3],[-1,7]])
s=np.array([[5,2],[1,2]])
print(r)
print('***')
print(s)


[[ 1  3]
 [-1  7]]
***
[[5 2]
 [1 2]]


In [67]:
r*2 + 4*

array([[ 2,  6],
       [-2, 14]])

In [70]:
i=np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [72]:
w=2*i+4*r+r@s
print(w)

[[14. 20.]
 [-2. 42.]]


In [13]:
b

array([3, 4, 5])

In [14]:
B=np.array([[3, 4, 5],[2, 6, 7],[3,-2,5]])
B

array([[ 3,  4,  5],
       [ 2,  6,  7],
       [ 3, -2,  5]])

In [15]:
np.linalg.det(B)

65.99999999999997

In [16]:
np.linalg.inv(B)

array([[ 0.66666667, -0.45454545, -0.03030303],
       [ 0.16666667, -0.        , -0.16666667],
       [-0.33333333,  0.27272727,  0.15151515]])

In [17]:
np.linalg.eig(B)

(array([8.62778979+0.j        , 2.68610511+0.65919568j,
        2.68610511-0.65919568j]),
 array([[-0.63643262+0.j        , -0.70579928+0.j        ,
         -0.70579928-0.j        ],
        [-0.76414906+0.j        , -0.52066136-0.13479085j,
         -0.52066136+0.13479085j],
        [-0.10502255+0.j        ,  0.46083845+0.01478071j,
          0.46083845-0.01478071j]]))

In [18]:
values,vectors=np.linalg.eig(B)

In [19]:
values

array([8.62778979+0.j        , 2.68610511+0.65919568j,
       2.68610511-0.65919568j])

In [20]:
vectors

array([[-0.63643262+0.j        , -0.70579928+0.j        ,
        -0.70579928-0.j        ],
       [-0.76414906+0.j        , -0.52066136-0.13479085j,
        -0.52066136+0.13479085j],
       [-0.10502255+0.j        ,  0.46083845+0.01478071j,
         0.46083845-0.01478071j]])

In [23]:
P=np.poly1d([2,5,0,-3])
print(np.poly1d(P))

   3     2
2 x + 5 x - 3


In [24]:
np.polyval(P,0)

-3

In [25]:
np.polyval(P,3)

96

In [26]:
w=np.poly1d([4,5,3,5,6,-1])
print(np.poly1d(w))

   5     4     3     2
4 x + 5 x + 3 x + 5 x + 6 x - 1


In [27]:
np.polyval(w,1)

22

In [28]:
n=np.poly1d([3,5,6,7])
print(np.poly1d(n))

   3     2
3 x + 5 x + 6 x + 7


In [29]:
n+w

poly1d([ 4,  5,  6, 10, 12,  6])

In [30]:
np.polyval(n+w,2)

326

In [32]:
(n+w)**3

poly1d([   64,   240,   588,  1325,  2658,  4458,  6564,  8934, 10944,
       11656, 10944,  9252,  6696,  3672,  1296,   216])